### PR TITLE
added some clearbit stuff

### PR DESCRIPTION
**Pull request by ryan280**
The clearbit.ts in the routes was mostly for testing because to make queries you need to have a clearbit api key. To use this api key when querying for a logo it can either be in the authentication of a header file or in a require statement as such `var clearbit = require('clearbit')('key');`. I dont think that it is possible to have a second param like this using `import from` because `import from` is clearly worse than require as discussed before. This makes me believe that we would have to use the header auth option passing our api key every time someone creates/updates an application. Or you know we could have just used require like any sane person :)

### CODE REVIEW

**Comment by roccopolimen** [comment]
Fixed Mike's silly code in 20 minutes that took him 2 weeks

**Comment by roccopolimen** [comment]
Can get rid of the stuff not being used like the clearbit route, and should also remove clearbit from package.json since we do not use that outdated package

**Comment by GraceMattern** [comment]
this took mike two weeks?! lol
Otherwise looks good

**Comment by roccopolimen** [comment]
small fix, and then pulled main in, LGTM

**Comment by mpolimen** [comment]
LGTM

**Pull request merged**
